feat: implement Cron feature and CommitStrip cron job
ES-Community/bot pull request #16
Opened 2020-10-24 17:26 UTC by targos

2020-10-24 17:43 UTC, Mesteery commented on src/crons/CommitStrip.ts
> +  const guild = client.guilds.cache.first();
Pourquoi ne pas directement utiliser l'identifiant du canal `gif` ?

2020-10-24 17:44 UTC, Sebastien-Ahkrin commented on src/crons/CommitStrip.ts
> +  const guild = client.guilds.cache.first();
je pense que le canal gif, n'a pas le même id sur ESC et sur nos discord de test  ^^

2020-10-24 17:48 UTC, Mesteery commented on src/crons/CommitStrip.ts
> +  const guild = client.guilds.cache.first();
J'y avais pas du tout pensé 😅

2020-10-24 17:54 UTC, Mesteery requested changes

2020-10-24 17:54 UTC, Mesteery commented on src/crons/CommitStrip.ts
> +  const guild = client.guilds.cache.first();
```diff
- const guild = client.guilds.cache.first();
- const channel = guild?.channels.cache.find(
-   (channel) => channel.type === 'text' && channel.name === 'gif',
- );
+ const channel = client.channels.cache.find(
+   (channel) => channel.type === 'text' && channel.name === 'gif',
+ );
```

2020-10-24 17:58 UTC, Mesteery commented on src/crons/CommitStrip.ts
> +  );
```suggestion
  const channel = client.channels.cache.find(
    (channel) => channel.type === 'text' && channel.name === 'gif',
  );
```

2020-10-24 18:04 UTC, targos commented on src/crons/CommitStrip.ts
> +  const guild = client.guilds.cache.first();
Oui c'est pour le récupérer dans avoir besoin de configurer l'ID sur chaque déploiement

2020-10-24 18:12 UTC, targos commented on src/crons/CommitStrip.ts
> +  );
A propos du cache, est-ce qu'on peut lui "faire confiance" ? Je me demande surtout s'il est prêt dès que le client est connecté

2020-10-24 18:15 UTC, Mesteery commented on src/crons/CommitStrip.ts
> +  );
Il faut attendre l'évènement `ready` avant de pouvoir utiliser le cache et autres propriétés de `Client`.
Il faut pas seulement attendre le login mais aussi le `ready` (`client.once('ready', ...)`)

2020-10-24 18:19 UTC, Mesteery commented on src/framework/Bot.ts
>        await this.client.login(this.token);
Atteindre l'événement `ready`.
```suggestion
      await this.client.login(this.token);
      await (new Promise((resolve) => client.once('ready', resolve)))
```

2020-10-24 19:31 UTC, targos commented on src/crons/CommitStrip.ts
> +  );
J'ai essayé de faire ce changement mais `client.channels.cache` contient des objets `Channel` qui n'ont pas de propriété `name`. `guild.channels.cache` contient des `GuildChannel` qui l'ont.

2020-10-24 19:35 UTC, targos commented on src/framework/Bot.ts
>        await this.client.login(this.token);
Fait dans https://github.com/ES-Community/bot/pull/16/commits/ddcf83d75c1bac03d1dcd13489e7d64f4247597b en utilisant [events.once](https://nodejs.org/dist/latest-v15.x/docs/api/events.html#events_events_once_emitter_name_options).

2020-10-24 20:19 UTC, Mesteery commented on src/crons/CommitStrip.ts
> +  );
Il devrait pas y avoir de problème puisqu'il y a le `type === "text"`

2020-10-24 20:24 UTC, targos commented on src/crons/CommitStrip.ts
> +  );
https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgYQDbAKYDt4F84BmUEIcA5ACbADOAxtBQHQBW1ZAUOxRragIZQMcelmrxemHAC4U6bDADcnAPTK4AUSiCArlHYT5jWgAs+WLBlTUjfExkYFgWCgAoXJsxdQBKOAF4APmFTc0tGGABPMCE-WPIYDAAPGDI4ADI04M8wrD4QGLiyAHNgAjJvJXZVOAAFPmo4CjIMLQxdfTkcRiLtYFQKa1pbY3tHKDEXbwB+IxCvQeHRp1d3OctfQKzQ1HCogr94pJT0zI9txlz8-0KSsoqgA

2020-10-24 20:31 UTC, Mesteery commented on src/crons/CommitStrip.ts
> +  );
Peut-être que le cast est dégueulasse dans ce cas, mais je préfère personnellement cast que chercher la guilde dans le cache et ensuite chercher dans la guilde le canal

https://tsplay.dev/qWJ1Zm

2020-10-25 18:26 UTC, Xstoudi commented on src/crons/CommitStrip.ts
> +  );
Il ne faut surtout pas faire de cast, c'est une erreur.
Le type Channel englobe tout : DMs, Text, Voice, Category, News et Store.
Le type GuildChannel englobe : Text, Voice, Category, News et Store.

Il est absolument nécessaire de filter les instances de TextChannel.

2020-10-25 18:50 UTC, Mesteery commented on src/crons/CommitStrip.ts
> +  );
C'est filter avec `channel.type === "text"`

2020-10-25 18:56 UTC, Xstoudi commented on src/crons/CommitStrip.ts
> +  );
Oui, mais le filter sur le type n'indique en rien à TS qu'il doit inférer en une instance de TextChannel.

2020-10-25 19:12 UTC, Mesteery commented on src/crons/CommitStrip.ts
> +  );
C'est vrai, il faut alors utiliser `channel instanceof TextChannel`.

2020-10-25 19:16 UTC, Mesteery commented on src/framework/helpers.ts
> +      channel.type === 'text' && (channel as TextChannel).name === name,
```suggestion
      channel instanceof TextChannel && channel.name === name,
```

2020-10-28 13:23 UTC, Xstoudi approved these changes
LGTM

2020-10-28 14:17 UTC, Sebastien-Ahkrin approved these changes
LGTM TOO 👍 :)

2020-10-28 14:20 UTC, Kawacrepe approved these changes

2020-10-28 16:23 UTC, Mesteery commented
https://discord.com/channels/157205145669599233/678671254990880779/769914952559362060

2020-10-28 16:26 UTC, Xstoudi commented
Y a-t-il une raison de pas le faire ?

2020-10-28 16:33 UTC, Mesteery commented
Non, je veux juste savoir si y a une raison

2020-10-28 16:39 UTC, Xstoudi commented
La doc ok pour moi 👍🏻

2020-10-28 16:43 UTC, merged